version: '3.8'

services:
  web:
    build: 
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_URL=http://api:3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - circlesfera-network

  api:
    build: ../CircleSfera-Backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ../CircleSfera-Backend:/app
      - /app/node_modules
      - /app/build
    command: npm run dev
    networks:
      - circlesfera-network

networks:
  circlesfera-network:
    driver: bridge
